### PR TITLE
Forward all logs to Conduit

### LINKED ISSUE #48: Feature: Leveled logging
### Feature description

The logs the wrapper sends to Conduit (implemented in #43) are sent with an "unknown" logging level (i.e. the logging level is `???`). It would be good to have proper, leveled, logs.

Additional info about the current logging implementation: https://github.com/ConduitIO/conduit-kafka-connect-wrapper/pull/43#discussion_r836684780

### LINKED ISSUE #56: Feature: Forward all logs to Conduit
### Feature description

Currently, the wrapper only forwards logs that it produces itself, the backing connector logs are ignored. We should make sure to forward any and all messages that are written to stderr or stdout back to Conduit so that they are included in Conduit logs.

Related comment: https://github.com/ConduitIO/conduit-kafka-connect-wrapper/pull/43#pullrequestreview-922925314

### PR DESCRIPTION
**Pull request by hariso**
Fixes #56, fixes #48.

This PR has a few parts:
* The wrapper itself now logs through `stderr`. Previously, I thought that way of logging doesn't work. However, that's not quite true. If a connector is outputting logs to stderr, the logs will be printed in Conduit as well, **if the log level is set to debug**.
* Given that logging is done through facades, with `slf4j` and `log4j` being most widely used, this PR is configuring the two mentioned facades to log to `stderr`.

- [x] Wrapper logs 
- [x] slf4j logs
- [x] log4j logs
- [x] Make log level configurable: This is only about the logs in the wrapper and the underlying connector. Currently, this doesn't work for log4j logs (see comment in code for the reason).~~All logs from the wrapper and the underlying connector will eventually be written as debug logs in Conduit!~~ 

**Notes about log4j**: 
1. I couldn't set up a real connector with log4j. It looks like https://github.com/microsoft/kafka-connect-cosmosdb/ uses it, but I couldn't pull the Docker images to test it (it kept telling me that my evaluation expired). However, I wrote a simple, dummy dependency and tested it with it.
2. There are generally two ways to approach log4j: one is to configure it directly and another is to set up a bridge between log4j and slf4j. The latter is not guaranteed to work in 100% of the cases, so I went with the first approach.

### CODE REVIEW

**Comment by hariso** [comment]
@lovromazgon @simonl2002 @maha-hajja ready for review. I'm working on unit tests.

**Comment by lovromazgon** [comment]
> All logs from the wrapper and the underlying connector will eventually be written as debug logs in Conduit!

When I was configuring the logger in the SDK I found out that logs from the plugin need to produce a JSON that follows [this struct](https://github.com/hashicorp/go-plugin/blob/2caaccbc4131bfef4b91c51a1446d5fd1eb2a1fe/log_entry.go#L11-L17), then go-plugin can figure out the level and so on (see how log messages are [parsed](https://github.com/hashicorp/go-plugin/blob/2caaccbc4131bfef4b91c51a1446d5fd1eb2a1fe/log_entry.go#L38)). If the plugin doesn't produce JSON, there are some [fallbacks](https://github.com/hashicorp/go-plugin/blob/2caaccbc4131bfef4b91c51a1446d5fd1eb2a1fe/client.go#L1118), but ideally we don't want to use the fallback.

So what I'm trying to say - can we configure log4j to produce this format? Then logs should be parsed and filtered based on the configured log level in Conduit.

**Comment by hariso** [comment]
> When I was configuring the logger in the SDK I found out that logs from the plugin need to produce a JSON that follows [this struct](https://github.com/hashicorp/go-plugin/blob/2caaccbc4131bfef4b91c51a1446d5fd1eb2a1fe/log_entry.go#L11-L17), then go-plugin can figure out the level and so on (see how log messages are [parsed](https://github.com/hashicorp/go-plugin/blob/2caaccbc4131bfef4b91c51a1446d5fd1eb2a1fe/log_entry.go#L38)). If the plugin doesn't produce JSON, there are some [fallbacks](https://github.com/hashicorp/go-plugin/blob/2caaccbc4131bfef4b91c51a1446d5fd1eb2a1fe/client.go#L1118), but ideally we don't want to use the fallback.
> 
> So what I'm trying to say - can we configure log4j to produce this format? Then logs should be parsed and filtered based on the configured log level in Conduit.

Ah, nice! I'll try it out now.

**Comment by hariso** [comment]
> > All logs from the wrapper and the underlying connector will eventually be written as debug logs in Conduit!
> 
> When I was configuring the logger in the SDK I found out that logs from the plugin need to produce a JSON that follows [this struct](https://github.com/hashicorp/go-plugin/blob/2caaccbc4131bfef4b91c51a1446d5fd1eb2a1fe/log_entry.go#L11-L17), then go-plugin can figure out the level and so on (see how log messages are [parsed](https://github.com/hashicorp/go-plugin/blob/2caaccbc4131bfef4b91c51a1446d5fd1eb2a1fe/log_entry.go#L38)). If the plugin doesn't produce JSON, there are some [fallbacks](https://github.com/hashicorp/go-plugin/blob/2caaccbc4131bfef4b91c51a1446d5fd1eb2a1fe/client.go#L1118), but ideally we don't want to use the fallback.

The above was super-useful. Printing the logs in JSON format made the logs appear in Conduit with exactly the same log level as in the wrapper or the underlying connector.

> So what I'm trying to say - can we configure log4j to produce this format? 

After a little fight with the classpath: we eventually made log4j produce logs in JSON format. 

> Then logs should be parsed and filtered based on the configured log level in Conduit.

OK, so you're suggesting that the connector prints all logs and then Conduit filters them?

**Comment by lovromazgon** [comment]
> OK, so you're suggesting that the connector prints all logs and then Conduit filters them?

Yes, that's what happens in Go connectors right now, if I'm not mistaken. In the future, we could also pass the log level from Conduit to the connector when it starts, so it can filter those logs and not even emit them, but I think it's fine already without this.

**Comment by lovromazgon** [comment]
Depends on the amount of trace logs 😛 If you think it's going to be a problem I'm ok with adding a specific log level in the wrapper connector. I'd rather have a general solution for all connectors of course, but that's a bigger undertaking.

That said, I propose to simply skip this for now, maybe run a test or two and tackle it if we actually spot an issue with this behavior.

**Comment by lovromazgon** [comment]
10 Mb/s sounds a lot! Ok, then I propose adding a simple configuration field to set the log level for the connector and let the default be `INFO`. WDYT?

**Comment by hariso** [comment]
> 10 Mb/s sounds a lot! Ok, then I propose adding a simple configuration field to set the log level for the connector and let the default be `INFO`. WDYT?

We have that configuration parameter, it's `wrapper.log.level` and the default value is as you mentioned. 

However, for the record, Lovro and I started chatting about this, I miscalculated the log rate. It's 10 MB/min, not per second.

**Review by lovromazgon — APPROVED** [review]

**Pull request merged**
